Fix styling
LethalCompany/LCAPI.Core pull request #31
Opened 2023-11-30 20:45 UTC by Redforce04

Fixes the styling of the plugin. It also adds some small documentation for developers maintaining it.

System attributes are now hidden and marked as autogenerated.

2023-12-04 17:13 UTC, MaxWasUnavailable requested changes

2023-12-04 17:13 UTC, MaxWasUnavailable commented on LethalAPI.Core/Interfaces/IConfig.cs
> +    [Description("Indicates whether or note the plugin should show debug logs in the console.")]
whether or **note** --> not*

2023-12-05 01:11 UTC, Redforce04 reviewed
Fixed the typo.

2023-12-06 17:47 UTC, MaxWasUnavailable approved these changes
Looks good

2023-12-06 17:58 UTC, merged